// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AbsoluteSearch(arg1:string,arg2:boolean):Promise<Array<main.FsInfo>>;

export function BackToLastDir():Promise<string>;

export function ChangeCurrentDir(arg1:string):Promise<void>;

export function FuseSearch(arg1:string,arg2:boolean):Promise<Array<main.FsInfo>>;

export function GetBase64ImageSrc(arg1:string):Promise<string>;

export function GetCurrentDir():Promise<string>;

export function Open(arg1:string):Promise<void>;
