// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbsoluteSearch(arg1, arg2) {
  return window['go']['main']['App']['AbsoluteSearch'](arg1, arg2);
}

export function BackToLastDir() {
  return window['go']['main']['App']['BackToLastDir']();
}

export function ChangeCurrentDir(arg1) {
  return window['go']['main']['App']['ChangeCurrentDir'](arg1);
}

export function FuseSearch(arg1, arg2) {
  return window['go']['main']['App']['FuseSearch'](arg1, arg2);
}

export function GetBase64ImageSrc(arg1) {
  return window['go']['main']['App']['GetBase64ImageSrc'](arg1);
}

export function GetCurrentDir() {
  return window['go']['main']['App']['GetCurrentDir']();
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}
